{{- if .Values.systemManager }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.name | default .Release.Name | quote}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  backendType: systemManager
  data:
  {{- range $key, $value := .Values.systemManager.data }}
    - key: {{ $value }}
      name: {{ $key }}
  {{- end }}
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: {{ .Values.name | default .Release.Name | quote }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
      labels:
        app.kubernetes.io/managed-by: Helm
{{- end }}
